image: node:18-alpine3.17

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - check
  - test
  - publish
  - deploy

check version:
  stage: check
  before_script:
    - apk add jq curl git bash
    - npm install npm-check-updates@16.10.12
    - git config --global user.name "$GITLAB_USER_LOGIN"
    - git config --global user.email "$GITLAB_USER_EMAIL"
  script:
    - ./pipeline/prepare.sh
  only:
    - schedules

tests:
  stage: test
  script:
    - yarn install
    - yarn test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    when: always
    paths:
      - coverage/lcov-report
    reports:
      junit:
        - junit.xml
  except:
    - schedules

publish_package_gitlab:
  stage: publish
  needs:
    - tests
  before_script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
  script:
    - yarn install
    - yarn build
    - npm publish
  only:
    - tags

publish_package_npm:
  stage: publish
  needs:
    - tests
  script:
    - yarn install
    - yarn build
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish --access public
  only:
    - tags

pages:
  stage: deploy
  needs:
    - publish_package_npm
    - tests
  dependencies:
    - tests
  script:
    - yarn install
    - node_modules/.bin/typedoc --theme node_modules/typedoc-neo-theme/bin/default/
    - cp -r coverage/lcov-report public
  artifacts:
    paths:
      - public
  only:
    - tags
