include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

image: node:16

stages:
  - test
  - publish
  - deploy

tests:
  stage: test
  script:
    - yarn install
    - yarn test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    when: always
    paths:
      - coverage/lcov-report
    reports:
      junit:
        - junit.xml

publish_package_gitlab:
  stage: publish
  needs:
    - tests
  before_script:
    - |
      {
        echo '@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_SERVER_PROTOCOL}://${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/'
        echo '//${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}'
        echo '//${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'
      } >> .npmrc
  script:
    - yarn install
    - yarn build
    - npm publish dist
  only:
    - tags

publish_package_npm:
  stage: publish
  needs:
    - tests
  script:
    - yarn install
    - yarn build
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish --access public
  only:
    - tags

pages:
  stage: deploy
  needs:
    - publish_package_npm
    - tests
  dependencies:
    - tests
  script:
    - yarn install
    - node_modules/.bin/typedoc --theme node_modules/typedoc-neo-theme/bin/default/
    - cp -r coverage/lcov-report public
  artifacts:
    paths:
      - public
  only:
    - tags
